services:
    python311:
        build:
            context: ./Docker
            dockerfile: dev.Dockerfile
        image: 'python311'
        working_dir: '/usr/src/app'
        volumes:
            - './src:/usr/src/app'
            - './cache:/root/.cache/pip'
        networks:
            - seoworker
        depends_on:
            zookeeper:
                condition: service_started
            kafka:
                condition: service_started
    zookeeper:
        restart: always
        image: docker.io/bitnami/zookeeper:latest
        ports:
            - "2181:2181"
        volumes:
            - "zookeeper-volume:/bitnami"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
            - seoworker
    kafka:
        restart: always
        image: docker.io/bitnami/kafka:latest
        ports:
            - "9093:9093"
            - "9092:9092"
        volumes:
            - "kafka-volume:/bitnami"
        networks:
            - seoworker
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
            - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
        depends_on:
            - zookeeper
networks:
    seoworker:
volumes:
    kafka-volume:
    zookeeper-volume:

